[versions]
sykepengerGradlePlugins = "20261001.1830"

[libraries]
jackson3-bom = "tools.jackson:jackson-bom:3.2.3"
kotlinx-coroutines-slf4j = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:1.11.0"
logback-classic = "ch.qos.logback:logback-classic:1.6.5"
logstash-logback-encoder = "net.logstash.logback:logstash-logback-encoder:9.0"
slf4jApi = "org.slf4j:slf4j-api:2.0.20"

[bundles]

[plugins]
sykepenger-kotlin = { id = "no.nav.sykepenger.kotlin", version.ref = "sykepengerGradlePlugins" }
sykepenger-root = { id = "no.nav.sykepenger.root", version.ref = "sykepengerGradlePlugins" }
