name: Bygg, test og publiser modul

on:
  workflow_call:
    inputs:
      modul:
        description: Navnet på modulen som skal bygges, testes og publiseres, f.eks. "logging"
        required: true
        type: string

jobs:
  bygg-test-og-publiser:
    name: Bygg, test og publiser
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: temurin
          java-version: 25

      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Generer versjon
        id: versjon
        run: |
          VERSJON=$(TZ=Europe/Oslo date +%Y%m%d.%H%M)
          echo "## Versjon $VERSJON" >> "$GITHUB_STEP_SUMMARY"
          echo "versjon=$VERSJON" >> "$GITHUB_OUTPUT"

      - name: gradlew build
        env:
          MODUL: ${{ inputs.modul }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew --build-cache ":$MODUL:build"

      - name: gradlew publish
        env:
          MODUL: ${{ inputs.modul }}
          VERSJON: ${{ steps.versjon.outputs.versjon }}
          ORG_GRADLE_PROJECT_githubPackagesUsername: x-access-token
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew --build-cache -Pversion="$VERSJON" ":$MODUL:publish"
